import Head from 'next/head'
import Link from 'next/link';
// import styles from '../styles/Home.module.css'
import { useState } from 'react';
import CrearCampo from '../components/CrearCampo';

export default function CrearModelo() {
  const [nombreModelo, setNombre] = useState();
  const [camposModelo, setCampos] = useState([]);
  const [listaModelos, setListaModelos] = useState([])

  const agregarCampo = () => {
    setCampos([...camposModelo, { nombre: '', tipo: '', esUnico: false, NotNull: true}]);
  };

  const agregarModelo = () => {
    setListaModelos([...listaModelos, {nombreTabla:nombreModelo, camposTabla:camposModelo}])
  }

  const eliminarPropiedad = (index) => {
    const nuevasPropiedades = [...camposModelo];
    nuevasPropiedades.splice(index, 1);
    setCampos(nuevasPropiedades);
  };

  const handleNombreChange = (valor, index) => {
    const nuevosCampos = [...camposModelo];
    nuevosCampos[index].nombre = valor;
    setCampos(nuevosCampos);
  };

  const handleUnicoChange = (valor, index) => {
    const nuevosCampos = [...camposModelo];
    nuevosCampos[index].esUnico = valor;
    setCampos(nuevosCampos);
  };

  const handleTipoChange = (valor, index) => {
    const nuevosCampos = [...camposModelo];
    nuevosCampos[index].tipo = valor;
    setCampos(nuevosCampos);
  };

  const handleNotNullChange = (valor, index) => {
    const nuevosCampos = [...camposModelo];
    nuevosCampos[index].NotNull = valor;
    setCampos(nuevosCampos);
  };

  //ACA SE PASAN LOS DATOS A LA API
  const handleSubmit = async (e) => {
    e.preventDefault();

    alert(JSON.stringify(listaModelos))

    const response = await fetch('/api/crearModelo', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({listaModelos: listaModelos})
    });

    if (response.ok) {
      alert("Se creo Correctamente");
    } else {
      alert('Error al crear el modelo');
    }

    //setCampos([{ esUnico: false }]);
    // setNombre([{ nombre: ''}])
  };

  return (
    <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className>
      <form onSubmit={handleSubmit}>
        <div>        
          <label>
            Nombre del Modelo:
            <input
              type="text"
              value={nombreModelo}
              onChange={(e) => setNombre(e.target.value)}
            />
          </label>
        </div>

        {camposModelo.map((campo, index) => (
          <CrearCampo
            key={index}
            nombreCampo={campo.nombre}
            onNombreChange={(valor) => handleNombreChange(valor, index)}
            onTipoChange={(valor) => handleTipoChange(valor, index)}
            onUnicoChange={(valor) => handleUnicoChange(valor, index)}
            onNotNullChange={(valor) => handleNotNullChange(valor, index)}
            onEliminar={() => eliminarPropiedad(index)}
          />
        ))}

        <button type="button" onClick={agregarCampo}>Agregar Campo al Modelo</button>
        <button type="button" onClick={agregarModelo}>Crear Modelo</button>
        <button type="submit" onClick={handleSubmit}>Submit</button>

      </form>

    </main>

    <footer>

    </footer>
  </div>
);
}
