import Head from 'next/head'
import Link from 'next/link';
import Menu from '../components/Menu';
import Footer from '../components/Footer'; 


export default function Index() {
  return (
    <div className="flex flex-col min-h-screen bg-zinc-950 text-white">
      <Head>
        <title>DBG</title>
        <Menu />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoDB.png" />
      </Head>

      <main className="flex-grow text-center">
      <h1 className="text-4xl font-bold mt-14 mb-4">Welcome to Database Generator</h1>
        <img src="database.png" alt="Logo" className="mx-auto mt-16 mb-16" style={{ width: '200px', height: '200px' }} />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
