import Head from 'next/head'
import Link from 'next/link';
// import styles from '../styles/Home.module.css'

export default function Index() {
  return (
    <div className="flex items-center justify-center h-screen bg-zinc-950 text-white">
      <Head>
        <title>DBG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <Link href='/login' className="text-blue-500 hover:underline">Login</Link>
        <h1 className="text-4xl font-bold mt-4">ESTO ES EL INDEX</h1>
      </main>

      <footer>
      </footer>
    </div>
  );
}
