import Head from 'next/head'
import Link from 'next/link';
import Footer from '../components/Footer'; 
// import styles from '../styles/Home.module.css'

export default function Index() {
  return (
    <div className="flex flex-col min-h-screen bg-zinc-950 text-white">
      <Head>
        <title>DBG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoDB.png" />
      </Head>

      <main className="flex-grow text-center">
      <h1 className="text-4xl font-bold mt-4 mb-4">Welcome to Database Generator</h1>
        <Link href='/login' className="text-blue-500 hover:underline">
          Login
        </Link>
        <img src="gendb.jpeg" alt="Logo" className="mx-auto mt-16 mb-16" style={{ width: '400px', height: '300px' }} />
        <h1 className="text-4xl font-bold mt-4">Start generating models </h1>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
