import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Sequelize } from 'sequelize';
import { useState } from 'react';
import CrearCampo from '../components/CrearCampo';

export default function CrearModelo() {
  const [nombre, setNombre] = useState('');
  const [Campos, setCampos] = useState([{ nombre: ''}]);

  const agregarCampo = () => {
    setCampos([...Campos, { nombre: '', esUnico : false }]);
  };

  const eliminarPropiedad = (index) => {
    const nuevasPropiedades = [...Campos];
    nuevasPropiedades.splice(index, 1);
    setCampos(nuevasPropiedades);
  };

  const handleNombreChange = (valor, index) => {
    const nuevosCampos = [...Campos];
    nuevosCampos[index].nombre = valor;
    setCampos(nuevosCampos);
  };

  const handleUnicoChange = (valor, index) => {
    const nuevosCampos = [...Campos];
    nuevosCampos[index].esUnico = valor;
    setCampos(nuevosCampos);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();





    setCampos([{ nombre: '', esUnico: '' },]);
  };

  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <form onSubmit={handleSubmit}>
        <div>        
          <label>
            Nombre del Modelo:
            <input
              type="text"
              value={nombre}
              onChange={(e) => setNombre(e.target.value)}
            />
          </label>
        </div>

        {Campos.map((campo, index) => (
          <CrearCampo
            key={index}
            nombreCampo={campo.nombre}
            onNombreChange={(valor) => handleNombreChange(valor, index)}
            onUnicoChange={(valor) => handleUnicoChange(valor, index)}
            onEliminar={() => eliminarPropiedad(index)}
          />
        ))}
        <button type="button" onClick={agregarCampo}>Agregar Propiedad</button>
        <button type="submit">Crear Modelo</button>
      </form>
    </main>

    <footer className={styles.footer}>

    </footer>
  </div>
);
}
